### ISSUE TITLE
QrCode is not scanning

### ISSUE THREAD

**Issue by nameisjayant** [nisaefendioglu/QR-Code-Scanner#2]
This code is not working in android version 12 , qr code is not scanning

**Comment by nisaefendioglu** [comment]
Hello, the application supports devices up to Api level 33. However, as a result of my research, I came to the conclusion that the [library](https://github.com/journeyapps/zxing-android-embedded) I used for the QR code in the application [does not work on some devices](https://github.com/journeyapps/zxing-android-embedded/issues/652). It won't work on some devices because of this library. To resolve this situation, the library needs to be updated. :'(

**Comment by nameisjayant** [comment]
okay, can you suggest me any library which works on above android 12

**Comment by nisaefendioglu** [comment]
I don't know what library you are looking for. You can search android libraries for android level 32.
